### ISSUE TITLE
Addition of Pages Memorized prior to App Download

### ISSUE THREAD

**Issue by rmm007** [OwaisQuadri/Hifdh-Tracker#68]
السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللّٰه,
How do I add pages that I’ve memorized before I installed the app without throwing off the entire averages and all of that? 

For example, let’s say I memorized 2 juz (~40 pages) before I downloaded the app, how do I say  I have done those already without messing up everything?

**Comment by OwaisQuadri** [comment]
و عليكم السلام ورحمة الله وبركاته
Thanks for your email. since the averages are calculated based on each
month, as long as you know which month you memorized those pages, you can
bulk log those pages for each month (starting at whenever you started
memorizing). so for example if you started memorizing in September, you can
bulk log (by pressing the '+' in the top right of the log tab) the pages
that you memorized in September, and so on. If you don't know the exact
amount, as long as the starting date is somewhat accurate, all the values
should average out. I hope that helps. May Allah make it easy for you to
complete your hifdh!
